DROP DATABASE VOITURE;

CREATE DATABASE VOITURE
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;



-- PHOTO
CREATE TABLE PHOTO (
    idPhoto    SERIAL PRIMARY KEY,
    nomPhoto   VARCHAR(42),
    datePhoto  DATE,
    idVoiture  INT REFERENCES VOITURE (idvoiture)
);


-- VOITURE
CREATE TABLE VOITURE (
    idVoiture SERIAL PRIMARY KEY,
    nomModele VARCHAR(42) REFERENCES MODELE       (nommodele),
    nomType   VARCHAR(42) REFERENCES TYPE_VOITURE (nomtype)
);


-- MARQUE
CREATE TABLE MARQUE (
    nomMarque         VARCHAR(42) PRIMARY KEY,
    paysOrigineMarque VARCHAR(42)
);


-- PREPARATEUR
CREATE TABLE PREPARATEUR (
    nomPreparateur   VARCHAR(42) PRIMARY KEY,
    paysOriginePrepa VARCHAR(42)
);


-- MOTEUR
CREATE TABLE MOTEUR (
    idMoteur   SERIAL PRIMARY KEY,
);